# 環境共通の設定
#
# This Docker Compose file can be used to quickly bootup Dgraph Zero
# and Alpha in different Docker containers.

# It mounts /tmp/data on the host machine to /dgraph within the
# container. You can change /tmp/data to a more appropriate location.
# Run `docker-compose up` to start Dgraph.
# NOTE: whitelisting is set to private address ranges, this is ONLY for a local setup
#       please change it accordingly for your production setup
#       more here https://dgraph.io/docs/deploy/dgraph-administration/#whitelisting-admin-operations
services:
  apollo-server:
    build:
      context: ../apps/backend
      dockerfile: ../../infra/backend.Dockerfile
    ports:
      - 4000:4000
    command: ["npm", "start"] # 実行commandは環境ごとに違うが、Dockerfileの方で定義する場合、変更の都度Buildが必要なためここで定義
  zero:
    image: dgraph/dgraph:latest
    volumes:
      - dgraph-zero-data:/dgraph
    ports:
      - 5080:5080
      - 6080:6080
    restart: on-failure
    command: dgraph zero --my=zero:5080
  alpha:
    image: dgraph/dgraph:latest
    volumes:
      - dgraph-alpha-data:/dgraph
    ports:
      - 8080:8080
      - 9080:9080
    restart: on-failure
    command: dgraph alpha --my=alpha:7080 --zero=zero:5080 --security whitelist=10.0.0.0/8,172.0.0.0/8,192.168.0.0/16,127.0.0.1
  zero-test:
    image: dgraph/dgraph:latest
    volumes:
      - dgraph-zero-test-data:/dgraph
    ports:
      - 5081:5081
      - 6081:6081
    restart: on-failure
    command: dgraph zero --my=zero-test:5081 --port_offset 1
  alpha-test:
    image: dgraph/dgraph:latest
    volumes:
      - dgraph-alpha-test-data:/dgraph
    ports:
      - 8081:8081
      - 9081:9081
    restart: on-failure
    command: dgraph alpha --my=alpha-test:7081 --zero=zero-test:5081 --security whitelist=10.0.0.0/8,172.0.0.0/8,192.168.0.0/16,127.0.0.1 --port_offset 1
volumes:
  dgraph-alpha-data:
  dgraph-zero-data:
  dgraph-alpha-test-data:
  dgraph-zero-test-data:
